# Generated by Django 5.1 on 2024-09-01 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('original_url', models.URLField(verbose_name='Website URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_url', models.URLField(verbose_name='From URL')),
                ('to_url', models.URLField(verbose_name='To URL')),
                ('transition_time', models.DateTimeField(auto_now_add=True, verbose_name='Transition time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_transitions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_transitions', to='site_management.website', verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Accessed at')),
                ('data_uploaded', models.PositiveIntegerField(default=0, verbose_name='Data uploaded')),
                ('data_downloaded', models.PositiveIntegerField(default=0, verbose_name='Data downloaded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='site_management.website', verbose_name='Website')),
            ],
        ),
    ]
